Test: %_topdir setup in ~/.rpmmacros
* If we don't have a `~/.rpmmacros` file, create it and have it set
  `%_topdir` to this directory.
* If it does exist, and contains the correct `%_topdir` entry already,
  leave it alone and carry on.
* If it exists and the `%_topdir` entry is wrong, someone's configured
  `rpmbuild` in a way that won't work here, so abort and let the
  developer figure out what he wants to do.

A better way to deal with this might be to override any existing
`%_topdir` macro, but I'm not sure of how to do that yet or the
implications of it.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,6 +1,14 @@
 #!/bin/bash
 set -e -o pipefail
 
+
 die() { echo "$(basename "$0"):" "$@"; exit 1; }
 
 rpmbuild --version >/dev/null || die "Please 'sudo yum install rpm-build'"
+
+basedir="$(cd $(dirname $0) && pwd -P)"
+topdir_macro="%_topdir $basedir"
+grep -s -q "^$topdir_macro\$" ~/.rpmmacros || {
+    [[ -e ~/.rpmmacros ]] && die "%_topdir in ~/.rpmmacros is wrong; aborting."
+    echo "$topdir_macro" > ~/.rpmmacros
+}
